name: Sync Google Sheet to Supabase

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios csvtojson

      - name: Fetch Google Sheet and Sync to Supabase
        env:
          SHEET_CSV_URL: "https://docs.google.com/spreadsheets/d/1ucwDh80ApKM76eTZ5pSpzHm8Z8aaTlav/export?format=csv"
          SUPABASE_URL: "https://xyrvhhpkfznazfadrmhy.supabase.co"
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          node <<EOF
          const axios = require('axios');
          const csv = require('csvtojson');

          const sheetUrl = process.env.SHEET_CSV_URL;
          const supabaseUrl = process.env.SUPABASE_URL;
          const accessToken = process.env.SUPABASE_ACCESS_TOKEN;

          const table = "ai_tools";

          async function main() {
            const response = await axios.get(sheetUrl);
            const jsonArray = await csv().fromString(response.data);

            for (const row of jsonArray) {
              await axios.post(
                `${supabaseUrl}/rest/v1/${table}`,
                row,
                {
                  headers: {
                    apikey: accessToken,
                    Authorization: `Bearer ${accessToken}`,
                    'Content-Type': 'application/json',
                    Prefer: 'resolution=merge-duplicates'
                  }
                }
              );
            }

            console.log("✅ Synced to Supabase!");
          }

          main().catch(err => {
            console.error("❌ Sync failed:", err.message);
            process.exit(1);
          });
          EOF
