name: Sync Google Sheet to Supabase

on:
  workflow_dispatch:
  push:
    paths:
      - 'supabase/functions/sync-sheet-ai-tools/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        run: |
          npm install -g supabase

      - name: Deploy Edge Function
        run: |
          supabase functions deploy sync-sheet-ai-tools --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
